#!/bin/env python

import argparse
import pyperclip

parser = argparse.ArgumentParser(
    description="PR Pass Generate passwords easily",
    add_help=True,
)

parser.add_argument('-p', '--plaint_text', dest='plain_text', required=1,
                    help="Get the passphrase")
parser.add_argument('-n', '--lucky_num', dest='lucky_num', default=0,
                    required=1, help="Get the lucky number", type=int)
parser.add_argument('-V', '--version', action='version',
                    version='%(prog)s 1.0.0')

try:
    arguments = parser.parse_args()
except Exception as e:
    print("Some Error Occured. Try reinstalling the package or updating to the latest version")
    exit(0)


class pr_pass(object):
    def __init__(self, num=None):
        self.sample = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
                       "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
                       "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "!", "@", "#", "$", "%", "^", "&", "*", '$', '?']
        self.def_lt = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
                       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
        self.data = {
            "0": {
                "a": "87yhj8ik",
                "b": "4eserds",
                "c": "54er",
                "d": "iuhj9ij",
                "e": "ui87yhj",
                "f": "87ygftyu",
                "g": "oijkokmn",
                "h": "9ijiok",
                "i": "6yh",
                "j": "7ujh",
                "k": "4rfr5rg",
                "l": "7uji",
                "m": "i9o0p",
                "n": "ujjuik",
                "o": "09io0",
                "p": "okmoplk",
                "q": "76yu7uj",
                "r": "y7ujju78",
                "s": "98ikj",
                "t": "uio8ikl",
                "u": "7ui88io",
                "v": "8iko0",
                "w": "4r5t6",
                "x": "8i9u",
                "y": "t6y7yg",
                "z": "78uhj",
                "A": "$ES$RFER",
                "B": "%TG%^YTTYHG",
                "C": "&^TGH",
                "D": "UHBUIKMNB",
                "E": "YHNMYUHJ",
                "F": "YGVYUGH",
                "G": "*&YHJIK",
                "H": "UHBIJNHJ",
                "I": "&*(*UHGHJ",
                "J": "*IKJ",
                "K": "YHNHUHM",
                "L": "YGVB",
                "M": "CFTGBHUJM",
                "N": "YGVYHNJI",
                "O": "(*UI(",
                "P": "YHNYUJH",
                "Q": "&^TGHU&J",
                "R": "^YH^&UYJ",
                "S": "(*&UJMNB",
                "T": "%^&^YH",
                "U": "%TGHJU&",
                "V": "YHNJI",
                "W": "TGBHUJMKO",
                "X": "&UJ*UH",
                "Y": "&U(IJN",
                "Z": "WERRDXXCV"
            },

            "1": {
                "a": "76tgh7uj",
                "b": "3wawesa",
                "c": "43we",
                "d": "uygh8uh",
                "e": "yu76tgh",
                "f": "76tfdrty",
                "g": "iuhjijnb",
                "h": "8uhuij",
                "i": "5tg",
                "j": "6yhg",
                "k": "3ede4ef",
                "l": "6yhu",
                "m": "u8i9o",
                "n": "yhhyuj",
                "o": "98ui9",
                "p": "ijniokj",
                "q": "65ty6yh",
                "r": "t6yhhy67",
                "s": "87ujh",
                "t": "yui7ujk",
                "u": "6yu77ui",
                "v": "7uji9",
                "w": "3e4r5",
                "x": "7i8y",
                "y": "r5t6tf",
                "z": "67ygh",
                "A": "#WA#EDWE",
                "B": "$RF$%TRRTGF",
                "C": "^%RFG",
                "D": "YGVYUJNBV",
                "E": "TGBNTYGH",
                "F": "TFCTYFG",
                "G": "&^TGHUJ",
                "H": "YGVUHBGH",
                "I": "^&*&YGFGH",
                "J": "&UJH",
                "K": "TGBGYGN",
                "L": "TFCV",
                "M": "XDRFVGYHN",
                "N": "TFCTGBHU",
                "O": "*&YU*",
                "P": "TGBTYHG",
                "Q": "^%RFGY^H",
                "R": "%TG%^YTH",
                "S": "*&^YHNBV",
                "T": "$%^%TG",
                "U": "$RFGHY^",
                "V": "TGBHU",
                "W": "RFVGYHNJI",
                "X": "^YH&YG",
                "Y": "^Y*UHB",
                "Z": "QWEESZZXC"
            },

            "2": {
                "a": "98ujk9ol",
                "b": "5rdrtf",
                "c": "65rt",
                "d": "oijk0ok",
                "e": "io98ujk",
                "f": "98uhgyui",
                "g": "poklpl,m",
                "h": "0okopl",
                "i": "7uj",
                "j": "8ikj",
                "k": "5tgt6th",
                "l": "8iko",
                "m": "o0p-[",
                "n": "ikkiol",
                "o": "-0op-",
                "p": "pl,p[;l",
                "q": "87ui8ik",
                "r": "u8ikki89",
                "s": "09olk",
                "t": "iop9ol;",
                "u": "8io99op",
                "v": "9olp-",
                "w": "5t6y7",
                "x": "9o0i",
                "y": "y7u8uh",
                "z": "89ijk",
                "A": "%RD%TGRT",
                "B": "^YH^&UYYUJH",
                "C": "*&YHJ",
                "D": "IJNIOL<MN",
                "E": "UJM<UIJK",
                "F": "UHBUIHJ",
                "G": "(*UJKOL",
                "H": "IJNOKMJK",
                "I": "*()(IJHJK",
                "J": "(OLK",
                "K": "UJMJIJ<",
                "L": "UHBN",
                "M": "VGYHNJIK<",
                "N": "UHBUJMKO",
                "O": ")(IO)",
                "P": "UJMUIKJ",
                "Q": "*&YHJI*K",
                "R": "&UJ&*IUK",
                "S": ")(*IK<MN",
                "T": "^&*&UJ",
                "U": "^YHJKI*",
                "V": "UJMKO",
                "W": "YHNJIK<LP",
                "X": "*IK(IJ",
                "Y": "*I)OKM",
                "Z": "ERTTFCCVB"
            },

            "3": {
                "a": "76tgh7uj",
                "b": "3wawesa",
                "c": "43we",
                "d": "uygh8uh",
                "e": "yu76tgh",
                "f": "76tfdrty",
                "g": "iuhjijnb",
                "h": "8uhuij",
                "i": "5tg",
                "j": "6yhg",
                "k": "3ede4ef",
                "l": "6yhu",
                "m": "u8i9o",
                "n": "yhhyuj",
                "o": "98ui9",
                "p": "ijniokj",
                "q": "65ty6yh",
                "r": "t6yhhy67",
                "s": "87ujh",
                "t": "yui7ujk",
                "u": "6yu77ui",
                "v": "7uji9",
                "w": "3e4r5",
                "x": "7i8y",
                "y": "r5t6tf",
                "z": "67ygh",
                "A": "#WA#EDWE",
                "B": "$RF$%TRRTGF",
                "C": "^%RFG",
                "D": "YGVYUJNBV",
                "E": "TGBNTYGH",
                "F": "TFCTYFG",
                "G": "&^TGHUJ",
                "H": "YGVUHBGH",
                "I": "^&*&YGFGH",
                "J": "&UJH",
                "K": "TGBGYGN",
                "L": "TFCV",
                "M": "XDRFVGYHN",
                "N": "TFCTGBHU",
                "O": "*&YU*",
                "P": "TGBTYHG",
                "Q": "^%RFGY^H",
                "R": "%TG%^YTH",
                "S": "*&^YHNBV",
                "T": "$%^%TG",
                "U": "$RFGHY^",
                "V": "TGBHU",
                "W": "RFVGYHNJI",
                "X": "^YH&YG",
                "Y": "^Y*UHB",
                "Z": "QWEESZZXC"
            },

            "4": {
                "a": "87yhj8ik",
                "b": "4eserds",
                "c": "54er",
                "d": "iuhj9ij",
                "e": "ui87yhj",
                "f": "87ygftyu",
                "g": "oijkokmn",
                "h": "9ijiok",
                "i": "6yh",
                "j": "7ujh",
                "k": "4rfr5rg",
                "l": "7uji",
                "m": "i9o0p",
                "n": "ujjuik",
                "o": "09io0",
                "p": "okmoplk",
                "q": "76yu7uj",
                "r": "y7ujju78",
                "s": "98ikj",
                "t": "uio8ikl",
                "u": "7ui88io",
                "v": "8iko0",
                "w": "4r5t6",
                "x": "8i9u",
                "y": "t6y7yg",
                "z": "78uhj",
                "A": "$ES$RFER",
                "B": "%TG%^YTTYHG",
                "C": "&^TGH",
                "D": "UHBUIKMNB",
                "E": "YHNMYUHJ",
                "F": "YGVYUGH",
                "G": "*&YHJIK",
                "H": "UHBIJNHJ",
                "I": "&*(*UHGHJ",
                "J": "*IKJ",
                "K": "YHNhuHM",
                "L": "YGVB",
                "M": "CFTGBHUJM",
                "N": "YGVYHNJI",
                "O": "(*UI(",
                "P": "YHNYUJH",
                "Q": "&^TGHU&J",
                "R": "^YH^&UYJ",
                "S": "(*&UJMNB",
                "T": "%^&^YH",
                "U": "%TGHJU&",
                "V": "YHNJI",
                "W": "TGBHUJMKO",
                "X": "&UJ*UH",
                "Y": "&U(IJN",
                "Z": "WERRDXXCV"
            },
            "sample": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h",
                "i",
                "j",
                "k",
                "l",
                "m",
                "n",
                "o",
                "p",
                "q",
                "r",
                "s",
                "t",
                "u",
                "v",
                "w",
                "x",
                "y",
                "z",
                "A",
                "B",
                "C",
                "D",
                "E",
                "F",
                "G",
                "H",
                "I",
                "J",
                "K",
                "L",
                "M",
                "N",
                "O",
                "P",
                "Q",
                "R",
                "S",
                "T",
                "U",
                "V",
                "W",
                "X",
                "Y",
                "Z",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                ")",
                "!",
                "@",
                "#",
                "$",
                "%",
                "^",
                "&",
                "*",
                "(",
                "{",
                "[",
                ":",
                ";",
                ">",
                ".",
                "<",
                ","
            ]
        }

        self.num = num

    def wrap(self, str):
        ans = []
        for i in range(0, len(str), 12):
            a = str[i:i+12]
            ans.append(a)
        return ans

    def add(self, a, b):
        if a == "":
            return b
        ans = ""
        if len(a) == len(b):
            for i in range(len(a)):
                ans += self.sample[(ord(a[i]) + ord(b[i])) % 72]
        else:
            for i in range(len(b)):
                ans += self.sample[(ord(a[i]) + ord(b[i])) % 72]
            ans += a[len(b):len(a)]
        return ans

    def gen_pass(self, password, num=None):
        if num == None:
            if self.num != None:
                luck = self.num
            else:
                return "Check docs again"
        else:
            luck = num

        luck1 = str(luck % 5)
        ans = ""
        for i in range(len(password)):
            a = password[i]
            if a in self.def_lt:
                ans += self.data[luck1][a]
            else:
                ans += a

        ans = self.wrap(ans)
        luck += 100
        luck %= 72
        ans1 = self.sample[luck]
        for i in range(1, 12):
            ans1 += (self.sample[ord(ans1[i-1]) % 72])

        for i in range(0, len(ans)):
            ans1 = self.add(ans1, ans[i])

        luck += len(password) + (len(ans) * len(password))
        luck %= 72
        char1 = self.sample[(luck % 26) + 26] + \
            self.sample[((luck + 111) % 10) + 52]
        char3 = self.sample[((luck + 222) % 10) + 62] + \
            self.sample[(luck + 300) % 26]
        # // console.log(char1, char3);

        luck = (len(password) * luck) % len(ans1)

        ans1 = ans1[0:luck] + char1 + ans1[luck:len(ans1)]

        luck += (len(password) + len(ans))
        luck %= len(ans1)

        ans1 = ans1[0:luck] + char3 + ans1[luck:len(ans1)]
        pyperclip.copy(ans1)
        return ans1


a = pr_pass(arguments.lucky_num)

print(a.gen_pass(arguments.plain_text))
